name: "awstfdeployment"
on:
  workflow_dispatch:

jobs:
  Plan_Dev:
    if: github.ref == 'refs/heads/develop'
    uses: aws-actions/configure-aws-credentials@v1
    with:
      aws-region: eu-west-1
      role-to-assume: ${{ secrets.IAMROLE_GITHUB }}



  Deploy_Dev:
    needs: Plan_Dev
    uses: RekhuGopal/gitreusableflows/.github/workflows/aws_tf_appy.yml@develop
    with:
      path: AWS-Multi-Region-Deployment
      tf_vars_file: dev.tfvars
      gh_environment: dev

