name: "06_AWSMultiRegionDeployment"
on:
  workflow_dispatch:

jobs:
  Plan_Dev:
    if: github.ref == 'refs/heads/develop'
    uses: massivenk/gitreusableflows/.github/workflows/aws_tf_plan.yml@develop
    with:
      path: AWS-Multi-Region-Deployment
      tf_vars_file: dev.tfvars
      gh_environment: dev
      role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
      role-session-name: GitHub-Action-Role
      aws-region: ${{ env.AWS_REGION }}

  Deploy_Dev:
    needs: Plan_Dev
    uses: massivenk/gitreusableflows/.github/workflows/aws_tf_appy.yml@develop
    with:
      path: AWS-Multi-Region-Deployment
      tf_vars_file: dev.tfvars
      gh_environment: dev
      role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
      role-session-name: GitHub-Action-Role
      aws-region: ${{ env.AWS_REGION }}
