name: AWS Multi Region Deployment

on:
  workflow_dispatch: {}

jobs:
  plan_dev:
    if: github.ref == 'refs/heads/main'
    uses: massivenk/actions-workflows-terraform/.github/workflows/aws_tf_plan.yml@develop
    with:
      path: aws-resources

  deploy_dev:
    needs: plan_dev
    uses: massivenk/actions-workflows-terraform/.github/workflows/aws_tf_apply.yml@develop
    with:
       path: aws-resources





