name: "Terraform"

on:
  push:
    branches:
      - develop

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        name: Checkout Repository
      - uses: aws-actions/configure-aws-credentials@v1-Node20
        with:
          role-to-assume: arn:aws:iam::204931786341:role/github-action-deployment-role
          role-session-name: GitHub-Action-Role
          aws-region: eu-west-1
    defaults:
      run:
        working-directory: SNS
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.1
          terraform_wrapper: false

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color

      - name: Terraform Apply
        run: terraform apply -auto-approve
